apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
type: Opaque
stringData:
  database-url: "postgresql+psycopg2://mlflow_user:ChangeThisSecurePassword123!@mlflow-db-instance.c4b8c0ogk8eu.us-east-1.rds.amazonaws.com:5432/mlflow"
